#index:
#    path: /
#    controller: App\Controller\DefaultController::index

program_index:
  path: /program
  controller: App\Controller\ProgramController::index

index:
  path: /
  controller: App\Controller\DefaultController::index
